import { mockBaseUrl, homePage } from '@/config/projectConfig';
import { getBreadcrumbNameMap } from '@/utils/menu';

export const menuList = [
  {
    children: null,
    code: 'react_index_page',
    component: null,
    icon: null,
    id: 'index',
    name: '首页',
    path: homePage,
    upperId: '0',
    url: null,
  },
  {
    children: [
      {
        children: null,
        code: 'access_home',
        component: null,
        icon: null,
        id: 'access_home',
        name: '配置',
        path: mockBaseUrl + '/access/home',
        upperId: 'access',
        url: null,
      },
      {
        children: null,
        code: 'access_add',
        component: null,
        icon: null,
        id: 'access_add',
        name: '添加权限',
        path: mockBaseUrl + '/access/add',
        upperId: 'access',
        url: null,
      },
    ],
    code: 'access',
    component: null,
    icon: null,
    id: 'access',
    name: '权限管理',
    path: mockBaseUrl + '/access',
    upperId: '1',
    url: null,
  },
  {
    children: null,
    code: 'access_home',
    component: null,
    icon: null,
    id: 'access_home',
    name: '配置',
    path: mockBaseUrl + '/access/home',
    upperId: 'access',
    url: null,
  },
  {
    children: null,
    code: 'access_add',
    component: null,
    icon: null,
    id: 'access_add',
    name: '添加权限',
    path: mockBaseUrl + '/access/add',
    upperId: 'access',
    url: null,
  },
  {
    children: [
      {
        children: null,
        code: 'home_class',
        component: null,
        icon: null,
        id: 'home_class',
        name: 'class',
        path: mockBaseUrl + '/home/class',
        upperId: 'home',
        url: null,
      },
      {
        children: null,
        code: 'home_hook',
        component: null,
        icon: null,
        id: 'home_hook',
        name: 'hook',
        path: mockBaseUrl + '/home/hook',
        upperId: 'home',
        url: null,
      },
    ],
    code: 'home',
    component: null,
    icon: null,
    id: 'home',
    name: 'home',
    path: mockBaseUrl + '/home',
    upperId: '1',
    url: null,
  },
  {
    children: null,
    code: 'home_class',
    component: null,
    icon: null,
    id: 'home_class',
    name: 'class',
    path: mockBaseUrl + '/home/class',
    upperId: 'home',
    url: null,
  },
  {
    children: null,
    code: 'home_hook',
    component: null,
    icon: null,
    id: 'home_hook',
    name: 'hook',
    path: mockBaseUrl + '/home/hook',
    upperId: 'home',
    url: null,
  },
  {
    children: null,
    code: 'export_excel',
    component: null,
    icon: null,
    id: 'export_excel',
    name: '导出Excel',
    path: mockBaseUrl + '/ExportExcel',
    upperId: '1',
    url: null,
  },
  {
    children: null,
    code: 'export_word',
    component: null,
    icon: null,
    id: 'export_word',
    name: '导出word',
    path: mockBaseUrl + '/ExportWord',
    upperId: '1',
    url: null,
  },
  {
    children: null,
    code: 'file_viewer',
    component: null,
    icon: null,
    id: 'file_viewer',
    name: '文件预览',
    path: mockBaseUrl + '/FileViewer',
    upperId: '1',
    url: null,
  },
  {
    children: null,
    code: 'VirtualList',
    component: null,
    icon: null,
    id: 'VirtualList',
    name: '虚拟列表',
    path: mockBaseUrl + '/VirtualList',
    upperId: '1',
    url: null,
  },
  {
    children: null,
    code: 'water_mark',
    component: null,
    icon: null,
    id: 'water_mark',
    name: '水印',
    path: mockBaseUrl + '/WaterMark',
    upperId: '1',
    url: null,
  },
  {
    children: null,
    code: '404',
    component: null,
    icon: null,
    id: '404',
    name: '404',
    path: mockBaseUrl + '/404',
    upperId: '1',
    url: null,
  },
];

const Router = [
  {
    path: homePage,
    hideInPanelTab: true,
  },
  {
    name: '权限管理',
    path: mockBaseUrl + '/access',
    icon: 'smile',
    routes: [
      {
        name: '权限管理',
        path: mockBaseUrl + '/access',
        redirect: mockBaseUrl + '/access/home',
        hideInMenu: true,
        icon: 'smile',
      },
      {
        name: '配置',
        path: mockBaseUrl + '/access/home',
        component: '@/pages/Access/Home',
        icon: 'smile',
      },
      {
        name: '添加权限',
        path: mockBaseUrl + '/access/add',
        component: '@/pages/Access/Add',
        icon: 'smile',
      },
    ],
  },
  {
    name: 'charts',
    path: mockBaseUrl + '/charts',
    routes: [
      {
        name: 'echarts',
        path: mockBaseUrl + '/charts',
        redirect: '/charts/echarts',
        hideInMenu: true,
        icon: 'smile',
      },
      {
        name: 'antd-charts',
        path: mockBaseUrl + '/charts/ACharts',
        component: '@/pages/Charts/ACharts',
        icon: 'smile',
      },
      {
        name: 'ECharts',
        path: mockBaseUrl + '/charts/Echarts',
        component: '@/pages/Charts/ECharts',
        icon: 'smile',
      },
    ],
  },
  {
    name: '增删改组件',
    path: mockBaseUrl + '/home',
    icon: 'smile',
    routes: [
      {
        name: 'class',
        path: mockBaseUrl + '/home',
        redirect: '/home/class',
        hideInMenu: true,
        icon: 'smile',
      },
      {
        name: 'class',
        path: mockBaseUrl + '/home/class',
        component: '@/pages/Component/class',
        icon: 'smile',
      },
      {
        name: 'hook',
        path: mockBaseUrl + '/home/hook',
        component: '@/pages/Component/hook',
        icon: 'smile',
      },
    ],
  },
  {
    name: '导出excel',
    path: mockBaseUrl + '/ExportExcel',
    component: '@/pages/ExportExcel',
    icon: 'smile',
  },
  {
    name: '导出word',
    path: mockBaseUrl + '/ExportWord',
    component: '@/pages/ExportWord',
    icon: 'smile',
  },
  {
    name: '文件预览',
    path: mockBaseUrl + '/FileViewer',
    component: '@/pages/FileViewer',
    icon: 'smile',
  },
  {
    name: '虚拟列表',
    path: mockBaseUrl + '/VirtualList',
    component: '@/pages/VirtualList',
    icon: 'smile',
  },
  {
    name: '水印',
    path: mockBaseUrl + '/WaterMark',
    component: '@/pages/WaterMark',
    icon: 'smile',
  },
  {
    path: '*',
    hideInPanelTab: true,
  },
];

export const breadcrumbNameMap = getBreadcrumbNameMap(menuList, Router);
