name: github pages

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install yarn -g
      - run: yarn
      - run: yarn build:pro
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          publish_dir: ./dist
